package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

func main() {
	if len(os.Args) < 3 {
		fmt.Println("Usage: gen-aaguid <input-json-file> <output-go-file>")
		os.Exit(1)
	}

	inputFile := os.Args[1]
	outputFile := os.Args[2]

	// Read the input JSON file
	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Printf("Error reading JSON file: %v\n", err)
		os.Exit(1)
	}

	// Parse the JSON data
	var aaguidMap map[string]string
	err = json.Unmarshal(data, &aaguidMap)
	if err != nil {
		fmt.Printf("Error parsing JSON: %v\n", err)
		os.Exit(1)
	}

	// Create output directory if it doesn't exist
	err = os.MkdirAll(filepath.Dir(outputFile), 0755)
	if err != nil {
		fmt.Printf("Error creating directory: %v\n", err)
		os.Exit(1)
	}

	// Create the output file
	f, err := os.Create(outputFile)
	if err != nil {
		fmt.Printf("Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	// Write the Go code
	fmt.Fprintf(f, "// Code generated by gen-aaguid; DO NOT EDIT.\n")
	fmt.Fprintf(f, "// Source: %s\n", filepath.Base(inputFile))
	fmt.Fprintf(f, "// Generated: %s\n\n", time.Now().In(time.UTC).Format(time.RFC3339))
	fmt.Fprintf(f, "package utils\n\n")
	fmt.Fprintf(f, "// GetAAGUIDDescription returns the description of an authenticator by its AAGUID\n")
	fmt.Fprintf(f, "func GetAAGUIDDescription(aaguid string) string {\n")
	fmt.Fprintf(f, "\tswitch aaguid {\n")

	// Add a special zero AAGUID for testing purposes
	fmt.Fprintf(f, "\t// Special zero AAGUID, primarily for testing purposes\n")
	fmt.Fprintf(f, "\tcase \"00000000-0000-0000-0000-000000000000\":\n\t\treturn \"Zero Authenticator\"\n\n")

	// Get all keys and sort them
	keys := make([]string, len(aaguidMap))
	var n int
	for k := range aaguidMap {
		keys[n] = k
		n++
	}
	sort.Strings(keys)

	// Write cases for each AAGUID from the JSON file, in sorted order
	for _, aaguid := range keys {
		name := aaguidMap[aaguid]
		// Escape quotes in the name if needed
		escapedName := strings.ReplaceAll(name, `"`, `\"`)
		fmt.Fprintf(f, "\tcase \"%s\":\n\t\treturn \"%s\"\n", aaguid, escapedName)
	}

	// Write the default case and closing braces
	fmt.Fprintf(f, "\tdefault:\n\t\treturn \"\"\n")
	fmt.Fprintf(f, "\t}\n")
	fmt.Fprintf(f, "}\n")

	fmt.Printf("Successfully generated %s with %d AAGUID entries\n", outputFile, len(aaguidMap))
}
